# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["%kernel.cache_dir%\\whoscored\\"]

    app.whoscored:
        class: AppBundle\Utils\WhoscoredProvider
        arguments: ["@doctrine.orm.entity_manager", "@app.cache"]

    app.form.type.season:
        class: AppBundle\Form\Type\SeasonType
        arguments: ["@app.whoscored"]
        tags:
            - { name: form.type }

    app.form.type.stage:
        class: AppBundle\Form\Type\StageType
        arguments: ["@app.whoscored"]
        tags:
            - { name: form.type }

    curl.request_collector:
        class: CurlBundle\DataCollector\CurlRequestCollector
        public: false
        tags:
            - { name: data_collector, template: 'CurlBundle:Collector:curl', id: 'curl.request_collector' }