# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    curl.default_options: {CURLOPT_RETURNTRANSFER : true, CURLOPT_FAILONERROR : true, CURLOPT_USERAGENT : 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:22.0) Gecko/20100101 Firefox/22.0', CURLOPT_ENCODING : 'gzip, deflate', CURLOPT_REFERER : 'http://www.whoscored.com'}

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["%kernel.cache_dir%\\whoscored\\"]

    app.whoscored:
        class: AppBundle\Utils\WhoscoredProvider
        arguments: ["@doctrine.orm.entity_manager", "@app.cache", "@curl.remote_http_kernel"]

    app.form.type.season:
        class: AppBundle\Form\Type\SeasonType
        arguments: ["@app.whoscored"]
        tags:
            - { name: form.type }

    app.form.type.stage:
        class: AppBundle\Form\Type\StageType
        arguments: ["@app.whoscored"]
        tags:
            - { name: form.type }

    curl.request_collector:
        class: CurlBundle\DataCollector\CurlRequestCollector
        arguments: ["@?curl.request_logger"]
        public: false
        tags:
            - { name: data_collector, template: 'CurlBundle:Collector:curl', id: 'curl.request_collector' }

    curl.request_logger:
        class: CurlBundle\Logger\CurlRequestLogger
        arguments: ["@?logger", "@?debug.stopwatch"]
        public: false
        tags:
            - { name: monolog.logger, channel: "curl" }

    curl.remote_http_kernel:
        class: CurlBundle\HttpKernel\RemoteHttpKernel
        arguments: ["%curl.default_options%", "@?curl.request_logger"]